class EnvironmentConsts:
    
    WORM_SPEED_ORIGINAL = 1
    WORM_SENSE_ORIGINAL = 50
    WORM_SWITCH_ORIGINAL = 0.5
    WORM_BASIC_LENGTH = 6
    WORM_EVOLVING_PROBABILITY_TRISECT = 0.333
    WORM_EVOLVING_PROBABILITY_BISECT = 0.5
    
    WORM_SIZE = 10
    APPLE_SIZE = 10
    APPLE_COUNT = 80
    
    INIT_GENERATION = 30
    INIT_POPULATION = 15
    INIT_SEED = 777
    
    
    
class DisplayConsts:
    WIDTH = 700
    HEIGHT = 700
    FRAME_SPEED = 70
    
    STATUS_FONT_SIZE = 19
    STATUS_FONT_X_POS = 10

    GAP = EnvironmentConsts.WORM_SIZE * EnvironmentConsts.WORM_BASIC_LENGTH
    
    
class ColorConsts:
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    BLUE = (0, 0, 255)
    GREEN = (0, 255, 0)
    RED = (255, 0, 0)
    GRAY = (50, 50, 50)
    BRIGHT_GRAY = (100, 100, 100)
    
    
class DirectionConsts:
    DIRECTION_LEFT = "LEFT"
    DIRECTION_UP = "UP"
    DIRECTION_RIGHT = "RIGHT"
    DIRECTION_DOWN = "DOWN"
    
    DIRECTIONS = [DIRECTION_LEFT, DIRECTION_UP, DIRECTION_RIGHT, DIRECTION_DOWN]
    
    DIRECTOIN_REVERSE = {
        DIRECTION_LEFT: DIRECTION_RIGHT,
        DIRECTION_RIGHT: DIRECTION_LEFT,
        DIRECTION_DOWN: DIRECTION_UP,
        DIRECTION_UP: DIRECTION_DOWN,
    }